# Prometheus Configuration for Docker Automation Suite
# Monitors containers, applications, and infrastructure

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'docker-automation-suite'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker metrics via cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # PowerShell Tools Application
  - job_name: 'powershell-tools'
    static_configs:
      - targets: ['powershell-tools:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Security Lab metrics
  - job_name: 'security-lab'
    static_configs:
      - targets: ['security-lab:8080']
    metrics_path: '/metrics'
    scrape_interval: 60s

  # Development Environment metrics
  - job_name: 'dev-environment'
    static_configs:
      - targets: ['dev-environment:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Database metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx metrics
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://powershell-tools:5985
        - http://security-lab:8080
        - http://dev-environment:3000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Container health checks
  - job_name: 'container-health'
    static_configs:
      - targets: ['docker-daemon:2376']
    metrics_path: '/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true

# Remote write configuration for long-term storage
remote_write:
  - url: "http://victoria-metrics:8428/api/v1/write"
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB