name: Daily README Update

on:
  schedule:
    # Run daily at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Allow manual triggering

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Update GitHub stats
        run: |
          python scripts/update-stats.py
        env:
          GITHUB_USERNAME: a-ariff
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update recent activity
        run: |
          python scripts/update-activity.py
        env:
          GITHUB_USERNAME: a-ariff
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📊 Daily README update - $(date +'%Y-%m-%d')" || exit 0
            git push
          fi