name: Link Check
on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'
permissions:
  contents: read
jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose --accept 200,999 README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
