name: Link Check and Linting
on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'
permissions:
  contents: read
jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: Lint Markdown files
        run: markdownlint README.md
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose --accept 200,999 --max-redirects 5 --retry-wait-time 2 --timeout 20 README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}