name: 'README Auto-Branch and PR'
# Trigger on pull_request and push when README.md changes on main
on:
  pull_request:
    paths:
      - 'README.md'
  push:
    branches:
      - main
    paths:
      - 'README.md'
# Set GITHUB_TOKEN permissions
permissions:
  contents: write
  pull-requests: write
jobs:
  auto-branch-readme:
    runs-on: ubuntu-latest
    steps:
      # Checkout with permissions
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # Set up git user
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      # Create branch with timestamp and PR
      - name: Create branch and pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/readme-$(date +"%Y%m%d-%H%M")
          base: main
          commit-message: 'chore: automated README update'
          title: 'chore: automated README update'
          body: |
            ## Automated README Update
            
            This PR was automatically created by the README Auto-Branch and PR workflow.
            
            ### Changes
            - README.md has been updated
            
            ### Branch
            - Branch: `update/readme-$(date +"%Y%m%d-%H%M")`
            
            Please review the changes and merge if appropriate.
          labels: |
            automation
            readme
          assignees: a-ariff
          draft: false
          delete-branch: true
